export enum ROLE_LIST {
  ADMIN = 'admin',
  OPERATOR = 'operator',
  COLLECTOR = 'collector',
  SHIPPER = 'shipper',
  CUSTOMER = 'customer',
}

export enum STATION_TYPE {
  WARD,
  DISTRICT,
  CITY,
}

export enum ORDER_STATUS {
  ORDER_CREATED,
  COLLECTOR_ON_THE_WAY_TO_PICKUP_ADDRESS,
  WAITING_CUSTOMER_BRING_TO_STATION,
  COLLECTOR_ON_THE_WAY_TO_STATION_1,
  ORDER_ARRIVED_STATION_1,
  ORDER_READY_TO_SHIP,
  ORDER_ON_THE_WAY_TO_RECEIVER,
  ORDER_HAS_BEEN_SHIPPED,
  WAITING_TO_TRANSIT_1,
  COLLECTOR_ON_THE_WAY_TO_STATION_2,
  ORDER_ARRIVED_STATION_2,
  WAITING_TO_TRANSIT_2,
  COLLECTOR_ON_THE_WAY_TO_STATION_3,
  ORDER_ARRIVED_STATION_3,
  WAITING_TO_TRANSIT_3,
  COLLECTOR_ON_THE_WAY_TO_STATION_4,
  ORDER_ARRIVED_STATION_4,
  WAITING_TO_TRANSIT_4,
}
